"""Renomeia tabela Processo para Prc_Cad

Revision ID: 05a9546ac826
Revises: 3585dc3c161b
Create Date: 2024-06-23 12:31:50.022370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05a9546ac826'
down_revision: Union[str, None] = '3585dc3c161b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prc_Cad',
    sa.Column('PRC_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_TIPO', sa.String(length=20), nullable=True),
    sa.Column('PRC_PAI', sa.Integer(), nullable=True),
    sa.Column('PRC_NIVEL', sa.Integer(), nullable=True),
    sa.Column('PRC_CODIGO', sa.String(length=20), nullable=True),
    sa.Column('PRC_NOME', sa.String(length=256), nullable=True),
    sa.Column('PRC_GERENCIAM', sa.String(length=256), nullable=True),
    sa.Column('PRC_MISSAO', sa.String(length=999), nullable=True),
    sa.Column('PRC_DONO_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_EXIG_QUALID', sa.String(length=999), nullable=True),
    sa.Column('PRC_INDICE_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_ENTREGA_CLI_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_TIME_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_CONHEC_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_MODELAGEM_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_ROTINA_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_COMPLIANCE_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_AUDITORIA_ID', sa.Integer(), nullable=True),
    sa.Column('TESTEMFF', sa.Integer(), nullable=True),
    sa.Column('PRC_DT_CADASTRO', sa.TIMESTAMP(), nullable=True),
    sa.Column('PRC_DT_ALTERACAO', sa.TIMESTAMP(), nullable=True),
    sa.Column('PRC_DT_EXCLUSAO', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_id')
    )
    op.drop_table('prc_cad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prc_cad',
    sa.Column('PRC_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_TIPO', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('PRC_PAI', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_NIVEL', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_CODIGO', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('PRC_NOME', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('PRC_GERENCIAM', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=256), nullable=True),
    sa.Column('PRC_MISSAO', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=999), nullable=True),
    sa.Column('PRC_DONO_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_EXIG_QUALID', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=999), nullable=True),
    sa.Column('PRC_INDICE_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ENTREGA_CLI_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_TIME_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_CONHEC_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ESTR_FISICA_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ESTR_LOGICA_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_MODELAGEM_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ROTINA_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_COMPLIANCE_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_AUDITORIA_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_DT_CADASTRO', mysql.TIMESTAMP(), nullable=True),
    sa.Column('PRC_DT_ALTERACAO', mysql.TIMESTAMP(), nullable=True),
    sa.Column('PRC_DT_EXCLUSAO', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Prc_Cad')
    # ### end Alembic commands ###
