"""criar_tabela_prc_cad

Revision ID: ffa8fc63941c
Revises: bb66a76e28f0
Create Date: 2024-06-27 19:57:56.715288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ffa8fc63941c'
down_revision: Union[str, None] = 'bb66a76e28f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GER_INDIC',
    sa.Column('GER_INDIC_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GER_INDIC_TIPO', sa.String(length=255), nullable=True),
    sa.Column('GER_INDIC_NOME', sa.String(length=255), nullable=True),
    sa.Column('GER_INDIC_RESPONS', sa.String(length=255), nullable=True),
    sa.Column('GER_INDIC_CALCULO', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('GER_INDIC_OBSERV', sa.Text(), nullable=True),
    sa.Column('GER_INDIC_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('GER_INDIC_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('GER_INDIC_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('GER_INDIC_ID')
    )
    op.create_table('GER_TIME',
    sa.Column('GER_TIME_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GER_TIME_NOME', sa.String(length=256), nullable=False),
    sa.Column('GER_TIME_SIGLA', sa.String(length=20), nullable=False),
    sa.Column('GER_TIME_LIDER_ID', sa.Integer(), nullable=True),
    sa.Column('GER_TIME_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('GER_TIME_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('GER_TIME_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('GER_TIME_ID')
    )
    op.create_table('GER_USUARIOS',
    sa.Column('GER_USU_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GER_USU_NOME', sa.String(length=256), nullable=False),
    sa.Column('GER_USU_EMAIL', sa.String(length=256), nullable=False),
    sa.Column('GER_USU_SENHA', sa.String(length=256), nullable=True),
    sa.Column('GER_USU_GRUPOPERMISSAO', sa.String(length=256), nullable=True),
    sa.Column('GER_USU_TIME', sa.String(length=256), nullable=True),
    sa.Column('GER_USU_OBSERVACOES', sa.String(length=999), nullable=False),
    sa.Column('GER_USU_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('GER_USU_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('GER_USU_DT_INATIVACAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('GER_USU_ID')
    )
    op.create_table('PRC_ANALISE_CUSTOS',
    sa.Column('PRC_ANALISE_CUSTOS_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_ID', sa.Integer(), nullable=False),
    sa.Column('PRC_ANALISE_CUSTOS_CUSTO_FIXO', sa.String(length=255), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_CUSTO_VARIAVEL', sa.String(length=255), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_CUSTO_TOTAL', sa.String(length=255), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_GASTOS_GERAIS', sa.String(length=255), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_INVESTIMENTO', sa.String(length=255), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_LUCRO', sa.String(length=255), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_ROIC', sa.String(length=255), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_OBSERVACOES', sa.Text(), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_ANALISE_CUSTOS_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ANALISE_CUSTOS_ID')
    )
    op.create_table('PRC_ATIV_CAD',
    sa.Column('PRC_ATIV_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_ID', sa.Integer(), nullable=False),
    sa.Column('PRC_ATIV_CODIGO', sa.String(length=20), nullable=False),
    sa.Column('PRC_ATIV_TITULO', sa.String(length=256), nullable=False),
    sa.Column('PRC_ATIV_ANEXOS', sa.String(length=256), nullable=True),
    sa.Column('PRC_ATIV_OBS', sa.String(length=999), nullable=True),
    sa.Column('PRC_ATIV_TIME_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_ATIV_DT_CADASTRO', sa.DateTime(), nullable=False),
    sa.Column('PRC_ATIV_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_ATIV_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ATIV_ID')
    )
    op.create_table('PRC_AUDITORIA',
    sa.Column('PRC_AUDITORIA_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_AUDITORIA_TIPO', sa.String(length=255), nullable=True),
    sa.Column('PRC_AUDITORIA_PERIODIC', sa.String(length=255), nullable=True),
    sa.Column('PRC_AUDITORIA_DESCRICAO', sa.Text(), nullable=True),
    sa.Column('PRC_AUDITORIA_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_AUDITORIA_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_AUDITORIA_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_AUDITORIA_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_AUDITORIA_ID')
    )
    op.create_table('PRC_CAPAC_OPERAC',
    sa.Column('PRC_CAPAC_OPERAC_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_CAPAC_OPERAC_ELEMEN', sa.String(length=255), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_UN_MED', sa.String(length=255), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_VALOR', sa.String(length=255), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_DESCR', sa.Text(), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_CAPAC_OPERAC_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_CAPAC_OPERAC_ID')
    )
    op.create_table('PRC_COMPLIANCE',
    sa.Column('PRC_COMPLIANCE_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_COMPLIANCE_TIPO_REGRA', sa.String(length=255), nullable=True),
    sa.Column('PRC_COMPLIANCE_DESCR_REGRA', sa.Text(), nullable=True),
    sa.Column('PRC_COMPLIANCE_SITUACAO_REGRA', sa.String(length=255), nullable=True),
    sa.Column('PRC_COMPLIANCE_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_COMPLIANCE_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_COMPLIANCE_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_COMPLIANCE_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_COMPLIANCE_ID')
    )
    op.create_table('PRC_CONHEC',
    sa.Column('PRC_CONHEC_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_CONHEC_TEC', sa.Text(), nullable=True),
    sa.Column('PRC_CONHEC_GEST', sa.Text(), nullable=True),
    sa.Column('PRC_CONHEC_RELAC', sa.Text(), nullable=True),
    sa.Column('PRC_CONHEC_DESCR', sa.Text(), nullable=True),
    sa.Column('PRC_CONHEC_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_CONHEC_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_CONHEC_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_CONHEC_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_CONHEC_ID')
    )
    op.create_table('PRC_ENTREGA_CLI',
    sa.Column('PRC_ENTREGA_CLI_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_ID', sa.Integer(), nullable=False),
    sa.Column('PRC_ENTREGA_CLI_DESCR', sa.Text(), nullable=True),
    sa.Column('PRC_ENTREGA_CLI_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_ENTREGA_CLI_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_ENTREGA_CLI_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_ENTREGA_CLI_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ENTREGA_CLI_ID')
    )
    op.create_table('PRC_ESTR_FISICA',
    sa.Column('PRC_ESTR_FISICA_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_ESTR_FISICA_DESCR', sa.Text(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_NECESSID', sa.Text(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_ESTR_FISICA_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ESTR_FISICA_ID')
    )
    op.create_table('PRC_ESTR_LOGICA',
    sa.Column('PRC_ESTR_LOGICA_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_ESTR_LOGICA_DESCR', sa.Text(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_NECESSID', sa.Text(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_ESTR_LOGICA_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ESTR_LOGICA_ID')
    )
    op.create_table('PRC_FORNE_ITENS_CONS',
    sa.Column('PRC_FORNE_ITENS_CONS_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_FORNE_ITENS_CONS_NOME', sa.String(length=255), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_UN_MED', sa.String(length=20), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_VALOR', sa.String(length=20), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_FORNE_ITENS_CONS_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_FORNE_ITENS_CONS_ID')
    )
    op.create_table('PRC_MODELAGEM',
    sa.Column('PRC_MODELAGEM_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_MODELAGEM_TIPO', sa.String(length=255), nullable=True),
    sa.Column('PRC_MODELAGEM_DESCR', sa.Text(), nullable=True),
    sa.Column('PRC_MODELAGEM_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_MODELAGEM_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_MODELAGEM_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_MODELAGEM_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_MODELAGEM_ID')
    )
    op.create_table('PRC_ROTINA',
    sa.Column('PRC_ROTINA_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_ROTINA_TIPO', sa.String(length=255), nullable=True),
    sa.Column('PRC_ROTINA_START', sa.String(length=255), nullable=True),
    sa.Column('PRC_ROTINA_DESCR', sa.Text(), nullable=True),
    sa.Column('PRC_ROTINA_OBSERV', sa.Text(), nullable=True),
    sa.Column('PRC_ROTINA_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRC_ROTINA_DT_ALTERACAO', sa.DateTime(), nullable=True),
    sa.Column('PRC_ROTINA_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ROTINA_ID')
    )
    op.create_table('PRJ_GESTAO',
    sa.Column('PRJ_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRJ_TIPO', sa.String(length=20), nullable=False),
    sa.Column('PRJ_PAI', sa.Integer(), nullable=True),
    sa.Column('PRJ_NIVEL', sa.Integer(), nullable=False),
    sa.Column('PRJ_CODIGO', sa.String(length=20), nullable=False),
    sa.Column('PRJ_TITULO', sa.String(length=256), nullable=False),
    sa.Column('PRJ_DESCRICAO', sa.String(length=999), nullable=True),
    sa.Column('PRJ_RESPONS_ID', sa.Integer(), nullable=True),
    sa.Column('PRJ_EXECUTORES_ID', sa.Integer(), nullable=True),
    sa.Column('PRJ_PROCESSO_ID', sa.Integer(), nullable=True),
    sa.Column('PRJ_AREA', sa.String(length=256), nullable=True),
    sa.Column('PRJ_OBSERV_HISTOR', sa.String(length=999), nullable=True),
    sa.Column('PRJ_DT_CRIACAO', sa.DateTime(), nullable=False),
    sa.Column('PRJ_DT_PREVISTA', sa.DateTime(), nullable=True),
    sa.Column('PRJ_DT_PRORROGADA', sa.DateTime(), nullable=True),
    sa.Column('PRJ_DT_CONCLUSAO', sa.DateTime(), nullable=True),
    sa.Column('PRJ_DT_EXCLUSAO', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('PRJ_ID')
    )
    op.create_table('Prc_Cad',
    sa.Column('PRC_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('PRC_CODIGO', sa.String(length=19), nullable=True),
    sa.Column('PRC_MP_PAI', sa.Integer(), nullable=True),
    sa.Column('PRC_NIVEL', sa.Integer(), nullable=True),
    sa.Column('PRC_NOME', sa.String(length=256), nullable=True),
    sa.Column('PRC_OBJETIVO', sa.String(length=512), nullable=True),
    sa.Column('PRC_CONHEC_TEC_NOTA', sa.Integer(), nullable=True),
    sa.Column('PRC_CONHEC_GEST_NOTA', sa.Integer(), nullable=True),
    sa.Column('PRC_CONHEC_RELAC_NOTA', sa.Integer(), nullable=True),
    sa.Column('PRC_CONHEC_DESC_OBS', sa.String(length=512), nullable=True),
    sa.Column('PRC_ESTR_FISICA_NOTA', sa.Integer(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_DESCR', sa.String(length=512), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_NOTA', sa.Integer(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_DESCR', sa.String(length=512), nullable=True),
    sa.Column('PRC_TIME_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_ROTINA_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_COMPLIANCE_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_AUDITORIA_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_MODELAGEM_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_RECURSOS_UTILIZ_ID', sa.Integer(), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS', sa.String(length=256), nullable=True),
    sa.Column('PRC_DT_CADASTRO', sa.TIMESTAMP(), nullable=False),
    sa.Column('PRC_DT_ALTERACAO', sa.TIMESTAMP(), nullable=True),
    sa.Column('PRC_DT_EXCLUSAO', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_id')
    )
    op.drop_table('ger_time')
    op.drop_table('prj_gestao')
    op.drop_table('prc_conhec')
    op.drop_table('prc_entrega_cli')
    op.drop_table('prc_analise_custos')
    op.drop_table('ger_usuarios')
    op.drop_table('prc_capac_operac')
    op.drop_table('prc_compliance')
    op.drop_table('ger_indic')
    op.drop_table('prc_ativ_cad')
    op.drop_table('prc_forne_itens_cons')
    op.drop_table('prc_cad')
    op.drop_table('prc_rotina')
    op.drop_table('prc_estr_fisica')
    op.drop_table('prc_estr_logica')
    op.drop_table('prc_auditoria')
    op.drop_table('prc_modelagem')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prc_modelagem',
    sa.Column('PRC_MODELAGEM_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_MODELAGEM_TIPO', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_MODELAGEM_DESCR', mysql.TEXT(), nullable=True),
    sa.Column('PRC_MODELAGEM_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_MODELAGEM_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_MODELAGEM_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_MODELAGEM_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_MODELAGEM_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_auditoria',
    sa.Column('PRC_AUDITORIA_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_AUDITORIA_TIPO', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_AUDITORIA_PERIODIC', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_AUDITORIA_DESCRICAO', mysql.TEXT(), nullable=True),
    sa.Column('PRC_AUDITORIA_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_AUDITORIA_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_AUDITORIA_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_AUDITORIA_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_AUDITORIA_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_estr_logica',
    sa.Column('PRC_ESTR_LOGICA_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_ESTR_LOGICA_DESCR', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_NECESSID', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_ESTR_LOGICA_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_ESTR_LOGICA_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ESTR_LOGICA_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_estr_fisica',
    sa.Column('PRC_ESTR_FISICA_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_ESTR_FISICA_DESCR', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_NECESSID', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_ESTR_FISICA_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_ESTR_FISICA_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ESTR_FISICA_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_rotina',
    sa.Column('PRC_ROTINA_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_ROTINA_TIPO', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_ROTINA_START', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_ROTINA_DESCR', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ROTINA_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ROTINA_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_ROTINA_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_ROTINA_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ROTINA_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_cad',
    sa.Column('PRC_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_TIPO', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('PRC_PAI', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_NIVEL', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_CODIGO', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('PRC_NOME', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('PRC_GERENCIAM', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('PRC_MISSAO', mysql.VARCHAR(length=999), nullable=True),
    sa.Column('PRC_DONO_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_EXIG_QUALID', mysql.VARCHAR(length=999), nullable=True),
    sa.Column('PRC_INDICE_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ENTREGA_CLI_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_TIME_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_CONHEC_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ESTR_FISICA_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ESTR_LOGICA_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_MODELAGEM_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ROTINA_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_COMPLIANCE_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_AUDITORIA_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_DT_CADASTRO', mysql.TIMESTAMP(), nullable=True),
    sa.Column('PRC_DT_ALTERACAO', mysql.TIMESTAMP(), nullable=True),
    sa.Column('PRC_DT_EXCLUSAO', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_forne_itens_cons',
    sa.Column('PRC_FORNE_ITENS_CONS_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_FORNE_ITENS_CONS_NOME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_UN_MED', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_VALOR', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_FORNE_ITENS_CONS_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_FORNE_ITENS_CONS_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_FORNE_ITENS_CONS_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_ativ_cad',
    sa.Column('PRC_ATIV_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PRC_ATIV_CODIGO', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=20), nullable=True),
    sa.Column('PRC_ATIV_TITULO', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('PRC_ATIV_ANEXOS', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('PRC_ATIV_OBS', mysql.VARCHAR(length=999), nullable=True),
    sa.Column('PRC_ATIV_TIME_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRC_ATIV_DT_CADASTRO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_ATIV_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_ATIV_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ATIV_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ger_indic',
    sa.Column('GER_INDIC_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('GER_INDIC_TIPO', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GER_INDIC_NOME', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GER_INDIC_RESPONS', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('GER_INDIC_CALCULO', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('GER_INDIC_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('GER_INDIC_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('GER_INDIC_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('GER_INDIC_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('GER_INDIC_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_compliance',
    sa.Column('PRC_COMPLIANCE_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_COMPLIANCE_TIPO_REGRA', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_COMPLIANCE_DESCR_REGRA', mysql.TEXT(), nullable=True),
    sa.Column('PRC_COMPLIANCE_SITUACAO_REGRA', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_COMPLIANCE_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_COMPLIANCE_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_COMPLIANCE_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_COMPLIANCE_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_COMPLIANCE_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_capac_operac',
    sa.Column('PRC_CAPAC_OPERAC_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_CAPAC_OPERAC_ELEMEN', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_UN_MED', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_VALOR', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_DESCR', mysql.TEXT(), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_CAPAC_OPERAC_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_CAPAC_OPERAC_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_CAPAC_OPERAC_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ger_usuarios',
    sa.Column('GER_USU_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('GER_USU_NOME', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('GER_USU_EMAIL', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('GER_USU_SENHA', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('GER_USU_GRUPOPERMISSAO', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('GER_USU_TIME', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('GER_USU_OBSERVACOES', mysql.VARCHAR(length=999), nullable=False),
    sa.Column('GER_USU_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('GER_USU_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('GER_USU_DT_INATIVACAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('GER_USU_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_analise_custos',
    sa.Column('PRC_ANALISE_CUSTOS_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PRC_ANALISE_CUSTOS_CUSTO_FIXO', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_CUSTO_VARIAVEL', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_CUSTO_TOTAL', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_GASTOS_GERAIS', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_INVESTIMENTO', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_LUCRO', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_ROIC', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_OBSERVACOES', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_ANALISE_CUSTOS_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_ANALISE_CUSTOS_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ANALISE_CUSTOS_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_entrega_cli',
    sa.Column('PRC_ENTREGA_CLI_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_ID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PRC_ENTREGA_CLI_DESCR', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ENTREGA_CLI_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_ENTREGA_CLI_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_ENTREGA_CLI_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_ENTREGA_CLI_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_ENTREGA_CLI_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prc_conhec',
    sa.Column('PRC_CONHEC_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRC_CONHEC_TEC', mysql.TEXT(), nullable=True),
    sa.Column('PRC_CONHEC_GEST', mysql.TEXT(), nullable=True),
    sa.Column('PRC_CONHEC_RELAC', mysql.TEXT(), nullable=True),
    sa.Column('PRC_CONHEC_DESCR', mysql.TEXT(), nullable=True),
    sa.Column('PRC_CONHEC_OBSERV', mysql.TEXT(), nullable=True),
    sa.Column('PRC_CONHEC_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRC_CONHEC_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRC_CONHEC_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRC_CONHEC_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prj_gestao',
    sa.Column('PRJ_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PRJ_TIPO', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('PRJ_PAI', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRJ_NIVEL', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PRJ_CODIGO', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('PRJ_TITULO', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('PRJ_DESCRICAO', mysql.VARCHAR(length=999), nullable=True),
    sa.Column('PRJ_RESPONS_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRJ_EXECUTORES_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRJ_PROCESSO_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('PRJ_AREA', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('PRJ_OBSERV_HISTOR', mysql.VARCHAR(length=999), nullable=True),
    sa.Column('PRJ_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('PRJ_DT_PREVISTA', mysql.DATETIME(), nullable=True),
    sa.Column('PRJ_DT_PRORROGADA', mysql.DATETIME(), nullable=True),
    sa.Column('PRJ_DT_CONCLUSAO', mysql.DATETIME(), nullable=True),
    sa.Column('PRJ_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('PRJ_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ger_time',
    sa.Column('GER_TIME_ID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('GER_TIME_NOME', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('GER_TIME_SIGLA', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('GER_TIME_LIDER_ID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GER_TIME_DT_CRIACAO', mysql.DATETIME(), nullable=False),
    sa.Column('GER_TIME_DT_ALTERACAO', mysql.DATETIME(), nullable=True),
    sa.Column('GER_TIME_DT_EXCLUSAO', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('GER_TIME_ID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Prc_Cad')
    op.drop_table('PRJ_GESTAO')
    op.drop_table('PRC_ROTINA')
    op.drop_table('PRC_MODELAGEM')
    op.drop_table('PRC_FORNE_ITENS_CONS')
    op.drop_table('PRC_ESTR_LOGICA')
    op.drop_table('PRC_ESTR_FISICA')
    op.drop_table('PRC_ENTREGA_CLI')
    op.drop_table('PRC_CONHEC')
    op.drop_table('PRC_COMPLIANCE')
    op.drop_table('PRC_CAPAC_OPERAC')
    op.drop_table('PRC_AUDITORIA')
    op.drop_table('PRC_ATIV_CAD')
    op.drop_table('PRC_ANALISE_CUSTOS')
    op.drop_table('GER_USUARIOS')
    op.drop_table('GER_TIME')
    op.drop_table('GER_INDIC')
    # ### end Alembic commands ###
